#if defined _discord_included_
  #endinput
#endif
#define _discord_included_

#pragma dynamic 32768;

#include <json>
#include <DateTime>

#include <discord/DiscordTypeExtensions>
#include <discord/DiscordPermission>
#include <discord/DiscordGatewayPayload>
#include <discord/DiscordActivity>
#include <discord/DiscordPresence>
#include <discord/DiscordException>
#include <discord/DiscordBot>
#include <discord/DiscordRequest>
#include <discord/DiscordWebHook>
#include <discord/DiscordObject>
#include <discord/DiscordAttachment>
#include <discord/DiscordRole>
#include <discord/DiscordUser>
#include <discord/DiscordEmoji>
#include <discord/DiscordGuildUser>
#include <discord/DiscordVoiceRegion>
#include <discord/DiscordChannel>
#include <discord/DiscordChannelMention>
#include <discord/DiscordGuild>
#include <discord/DiscordReaction>
#include <discord/DiscordMessage>